name: Olga Carvalho
markdown: kramdown
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  syntax_highlighter: rouge

# my contacts
author: Olga Carvalho
email: olgasofiacarvalho@gmail.com
linkedin: https://www.linkedin.com/in/olgasofiacarvalho/
github: https://github.com/OlgaCarvalho
